### ISSUE TITLE
Manage remotes

### ISSUE THREAD

**Issue by ghost** [consulo/consulo-git#2]
How to add/manage remote repos?
![bug](https://cloud.githubusercontent.com/assets/10781622/6519997/ee1d018e-c3f6-11e4-867f-d4f934072078.jpg)

**Comment by VISTALL** [comment]
Hi. Git plugin is based on Jetbrains sources. They dont implement this function. I dont think that i have time for implement this, but i will leave this issue open.

**Comment by VISTALL** [comment]
Oh, or they already added. I will check in near future
